ifeq ($(CONFIG_PROJECT_msm8937_tinno),y)
	dts-dirs += v12bnlite	
endif

ifeq ($(CONFIG_PROJECT_sdm450_tinno),y)
	dts-dirs += c860	
endif

ifeq ($(CONFIG_PROJECT_c800_tinno),y)
	dts-dirs += c800
endif

subdir-y	:= $(dts-dirs)
