#
# Makefile for the fingerprint drivers.
#

obj-y	+=  fp_drv/
obj-$(FINGERPRINT_CHIPONE_7152_QSEE) += chipone_7152qsee/
obj-$(FINGERPRINT_ELAN_96SA) += elan_96sa/
obj-$(FINGERPRINT_ELAN_519C) += elan_519c/
obj-$(FINGERPRINT_GOODIX_GF316M) += goodix_316m/
obj-$(FINGERPRINT_GOODIX_3208_QSEE) += goodix_3208qsee/
obj-$(FINGERPRINT_GOODIX_GF5216) += goodix_gf5216/
obj-$(FINGERPRINT_SILHEAD_6163) += silead_6163/

